update shared-resources destroy action

diff --git a/.github/workflows/shared_resources_destroy.yml b/.github/workflows/shared_resources_destroy.yml
--- a/.github/workflows/shared_resources_destroy.yml
+++ b/.github/workflows/shared_resources_destroy.yml
@@ -46,16 +46,17 @@ jobs:
           TF_VAR_key_name: ${{ secrets.KEY_NAME }}
 
         run: |
-          # set the terraform workspace
-          export TF_WORKSPACE=$WORKSPACE
-          export VAR_FILE=env-configs/${TF_WORKSPACE}.tfvars
-
-          terraform -chdir=terraform/live/shared-resources \
+          export VAR_FILE=env-configs/${WORKSPACE}.tfvars
+          terraform -chdir=terraform/dev-envs/shared-resources \
             init \
             -backend-config="bucket=${TF_BACKEND_BUCKET}" \
             -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=shared-resources"
+          # create the workspace if it doesn't exist already
+          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+          # set the TF_WORKSPACE environment variable
+          export TF_WORKSPACE=$WORKSPACE
 
           terraform -chdir=terraform/live/shared-resources destroy -auto-approve
