fix workspace issue

diff --git a/.github/workflows/shared_resources_create_update.yml b/.github/workflows/shared_resources_create_update.yml
--- a/.github/workflows/shared_resources_create_update.yml
+++ b/.github/workflows/shared_resources_create_update.yml
@@ -45,13 +45,7 @@ jobs:
           TF_VAR_key_name: ${{ secrets.KEY_NAME }}
 
         run: |
-          # set the terraform workspace
-          # create the workspace if it doesn't exist already
-          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
-          # set the TF_WORKSPACE environment variable
-          export TF_WORKSPACE=$WORKSPACE
           export VAR_FILE=env-configs/${TF_WORKSPACE}.tfvars
-
           terraform -chdir=terraform/dev-envs/shared-resources \
             init \
             -backend-config="bucket=${TF_BACKEND_BUCKET}" \
@@ -59,6 +53,10 @@ jobs:
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=shared-resources"
+          # create the workspace if it doesn't exist already
+          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+          # set the TF_WORKSPACE environment variable
+          export TF_WORKSPACE=$WORKSPACE
 
           terraform -chdir=terraform/dev-envs/shared-resources \
             plan \
